### ISSUE TITLE
Preprocessing pipeline

### ISSUE THREAD

**Issue by YasmineMH1997** [vkola-lab/ncomms2022#10]
I have been trying to use your pipleine preprocessing on the OASIS3 dataset (Tw1). 
But nothing seems to happen. May you please guide me on how to properly use it. 
<img width="879" alt="image" src="https://github.com/vkola-lab/ncomms2022/assets/128826190/25798aa4-ad24-4bd6-9efb-3e28415e8854">

**Comment by shangranq** [comment]
Hi, the way to use the pipeline.sh through terminal can be found from the line 86 in pipeline.py, as below

call('bash pipeline.sh ' + path + ' ' + name + ' ' + root_folder + ' ' + step_7_f + ' ' + step_7_g, shell=True)

Comparing with your command, the missing parts are the argument "step_7_f" and "step_7_g". It should be helpful to refer to pipeline.py for more details of using it. The python script is just a for loop wrapper of the bash call to process all files from your data folder.
