### ISSUE TITLE
Question about demo

### ISSUE THREAD

**Issue by Eros1on-Aqua** [vkola-lab/ncomms2022#2]
Hi, I ran demo_inference.py and got these results. They are not consistent with the given label. Is this right?

filename	      	ADD_score	ADD_pred	COG_score	COG_pred	COG	ADD
demo1.npy	0.99999815	1		1.0072571	1		1	0
demo2.npy	0.007306823	0		1.2147483	1		0	0
demo3.npy	0.9996529	1		0.53027755	1		2	1
demo4.npy	0.99970007	1		0.7140738	1		2	0

Thanks a lot!

**Comment by shangranq** [comment]
Hi, thank you for raising the issue! I reproduced the result you got and realized the demo labels may not match with the MRI samples. I have updated the demo cases in the latest commit and also submitted the output file after running demo_inference.py. If you run it one more time, you should be able to get the same output. Thanks!
