### ISSUE TITLE
can not find T1.nii

### ISSUE THREAD

**Issue by xywhat** [vkola-lab/ncomms2022#3]

**Comment by shangranq** [comment]
We didn't provide the original MRI data in this repo, instead, we provided guideline on how to apply for access to data from different study centers. See an example here 
https://github.com/vkola-lab/ncomms2022/tree/main/lookupcsv/raw_tables/ADNI

**Comment by HanHenryOnlyFaceany** [comment]
如何去搜索下载对应csv的文件，面对多个筛选项，例如ADNI，OASIS，NACC等公开数据集
