### ISSUE TITLE
How to transform mri to npy?

### ISSUE THREAD

**Issue by xywhat** [vkola-lab/ncomms2022#4]
THANKS!

**Comment by shangranq** [comment]
The original data format for MRI is nifti (.nii extension). To convert from .nii to .npy, you can use the nibabel package. 

https://nipy.org/nibabel/gettingstarted.html

**Comment by xywhat** [comment]
I have mentioned the author used ADNI dataset, and I download the ADNI
data. But I don't know which dataset should be selected specifically.
Thank you for you reply!!

shangranq ***@***.***> 于2023年5月7日周日 01:46写道：
