### ISSUE TITLE
Is the class Fusion_Model_Wrapper  part of the code incomplete?

### ISSUE THREAD

**Issue by Yueup** [vkola-lab/ncomms2022#5]
Looking forward to your reply

**Comment by shangranq** [comment]
No, the code is complete. The class Fusion_Model_Wrapper inherits from its parent class NonImg_Model_Wrapper which contains the most of the class methods. Thus, Fusion_Model_Wrapper can directly leverage the implementation from its parent class. 

For class inheritance, you can find more details online and below is just a bare minimal illustration
https://www.w3schools.com/python/python_inheritance.asp

**Comment by Yueup** [comment]
Thank you for your explanation! I’ll try to
 run your enlightening code later
