### ISSUE TITLE
installation issue from requirements.txt

### ISSUE THREAD

**Issue by XinQi7788** [vkola-lab/ncomms2022#6]
After creating a conda environment, use pip install -r requirements.txt, but encountered many ERRORs: No matching distribution found for many libraries. 

For instance, 
ERROR: Could not find a version that satisfies the requirement libpng==1.6.37 (from -r requirements.txt (line 40)) (from versions: none)

Can you please update a new requirements.txt file to fix such issues? Thank you very much.

**Comment by shangranq** [comment]
Hey, we have just updated the requirements.txt file. Please let us know if you run into other issue when setting up the environment.

**Comment by XinQi7788** [comment]
I created a conda environment with python=3.8, then pip install -r requirements.txt using the latest updated one, but still got errors as below.

![image](https://user-images.githubusercontent.com/77089761/236884220-36c87bbb-642b-41bc-9b65-c0d898871a13.png)

Thanks
Xin
