### ISSUE TITLE
如何去搜索下载对应csv的文件，面对多个选项，例如ADNI，OASIS，NACC等公开数据集，希望能得到您的回复！

### ISSUE THREAD

**Issue by HanHenryOnlyFaceany** [vkola-lab/ncomms2022#7]
![image](https://github.com/vkola-lab/ncomms2022/assets/75490877/db9f5022-90d2-4602-83de-50d1259acafc)
![image](https://github.com/vkola-lab/ncomms2022/assets/75490877/d4896825-0736-4c03-89e2-aa6c17b5f146)

**Comment by vkola-lab** [comment]
W

**Comment by lxwwang** [comment]
请问你下载好了数据吗？能否为我提供一下帮助
